apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
spec:
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: web1
          image: wrequiao/conversao-temperatura
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web1
spec:
  selector:
    app: web1
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
